// Definição dos 12 arquétipos junguianos clássicos, com análise técnica psicanalítica

const ARCHETYPES = {
  inocente: {
    id: 'inocente',
    name: 'O Inocente',
    epithet: 'O Peregrino de Fé Cândida',
    desire: 'Permanecer em segurança e experimentar a existência como fundamentalmente boa',
    fear: 'Ser punido por algo feito de forma errada; o colapso da confiança básica',
    shadow: 'Negação primitiva e recusa em reconhecer a ambivalência do objeto (cisão idealizante)',
    defenseMechanisms: 'Negação, idealização primária, formação reativa contra a agressividade',
    clinicalNote:
      'Corresponde ao polo de confiança básica descrito por Erikson e à posição esquizoparanoide de Klein quando cindida apenas para o polo "bom". Em excesso, indica evitação fóbica do conflito intrapsíquico e intolerância à ambiguidade depressiva.',
    symbol: 'pomba-e-ramo',
    element: 'a nascente clara',
  },
  orfao: {
    id: 'orfao',
    name: 'O Órfão',
    epithet: 'O Errante Sem Lar',
    desire: 'Pertencer, conectar-se com os outros de forma realista',
    fear: 'Ser deixado de fora, destacar-se ou ser abandonado novamente',
    shadow: 'Vitimização crônica e identificação projetiva de desamparo aprendido',
    defenseMechanisms: 'Identificação projetiva, regressão, dependência',
    clinicalNote:
      'Associado à ferida narcísica primária e ao apego ansioso-ambivalente (Bowlby/Ainsworth). Clinicamente aproxima-se de padrões de desamparo aprendido e de organizações de personalidade dependente quando fixado.',
    symbol: 'lanterna-quebrada',
    element: 'a estrada de terra batida',
  },
  guerreiro: {
    id: 'guerreiro',
    name: 'O Guerreiro',
    epithet: 'O Escudo Contra a Ruína',
    desire: 'Defender-se e aos outros; provar valor através de ação corajosa',
    fear: 'Vulnerabilidade percebida como fraqueza; impotência',
    shadow: 'Agressividade descarregada sem mentalização; crueldade e dominação',
    defenseMechanisms: 'Formação reativa contra o medo, identificação com o agressor, cisão',
    clinicalNote:
      'Reflete a pulsão agressiva (Trieb) organizada pelo Superego em função protetora do Ego. Descompensado, aproxima-se de traços de personalidade antissocial ou de compensação maníaca de uma fragilidade narcísica subjacente.',
    symbol: 'espada-e-escudo',
    element: 'o campo de batalha ao amanhecer',
  },
  cuidador: {
    id: 'cuidador',
    name: 'O Cuidador',
    epithet: 'A Mão que Ampara',
    desire: 'Proteger e cuidar dos outros; altruísmo',
    fear: 'Egoísmo e ingratidão; que o cuidado seja insuficiente',
    shadow: 'Martírio, controle disfarçado de cuidado, exploração da própria abnegação',
    defenseMechanisms: 'Formação reativa, altruísmo como defesa contra impulsos agressivos, sublimação',
    clinicalNote:
      'Relaciona-se à função de holding descrita por Winnicott. Quando rígido, pode mascarar hostilidade recalcada por meio de cuidado compulsivo — padrão próximo à codependência e a estruturas obsessivas do caráter.',
    symbol: 'calice-e-manto',
    element: 'o lar iluminado pela lareira',
  },
  explorador: {
    id: 'explorador',
    name: 'O Explorador',
    epithet: 'O Andarilho dos Confins',
    desire: 'Liberdade para descobrir quem se é através do mundo',
    fear: 'Aprisionamento, conformidade, vazio interior',
    shadow: 'Fuga compulsiva de vínculos; incapacidade de tolerar profundidade relacional',
    defenseMechanisms: 'Fuga (acting-out), isolamento do afeto, evitação de apego',
    clinicalNote:
      'Ligado à individuação junguiana em sua fase de separação. Em padrão rígido, aproxima-se de estilo de apego evitativo e de mecanismos de fuga (flight) frente à intimidade ou à estagnação psíquica.',
    symbol: 'bussola-e-trilha',
    element: 'a montanha distante',
  },
  sabio: {
    id: 'sabio',
    name: 'O Sábio',
    epithet: 'O Guardião do Saber Antigo',
    desire: 'Compreender o mundo através do conhecimento e da reflexão',
    fear: 'Ser enganado, ignorância, superficialidade',
    shadow: 'Intelectualização defensiva; dogmatismo que substitui a vivência afetiva',
    defenseMechanisms: 'Intelectualização, racionalização, isolamento do afeto',
    clinicalNote:
      'Corresponde à função pensamento (thinking function) na tipologia junguiana. Quando hipertrofiado, gera cisão entre cognição e afeto compatível com estilos esquizoides ou obsessivo-compulsivos do caráter.',
    symbol: 'livro-e-vela',
    element: 'a torre de pergaminhos',
  },
  rebelde: {
    id: 'rebelde',
    name: 'O Rebelde',
    epithet: 'O Quebrantador de Correntes',
    desire: 'Revolucionar o que não funciona; rupturas necessárias',
    fear: 'Ser impotente ou irrelevante; ser absorvido pelo sistema',
    shadow: 'Destrutividade pela destrutividade; rompimento como defesa contra o vínculo',
    defenseMechanisms: 'Atuação (acting-out), negativismo, cisão contra figuras de autoridade',
    clinicalNote:
      'Expressa a tensão edípica com a autoridade internalizada (Superego). Em sua forma sombria aproxima-se de traços de personalidade oposicionista-desafiadora ou de organizações borderline com instabilidade de vínculo à autoridade.',
    symbol: 'corrente-partida',
    element: 'a fortaleza em chamas',
  },
  mago: {
    id: 'mago',
    name: 'O Mago',
    epithet: 'O Alquimista das Transformações',
    desire: 'Compreender as leis fundamentais e transformar a realidade',
    fear: 'Consequências não intencionais; manipulação involuntária',
    shadow: 'Onipotência mágica de pensamento; manipulação instrumental do outro',
    defenseMechanisms: 'Onipotência, controle onisciente, cisão entre saber e agir',
    clinicalNote:
      'Aproxima-se do processo de individuação como transformação simbólica (self junguiano). Descompensado, assemelha-se ao pensamento mágico regressivo e a traços narcisistas de grandiosidade e controle onipotente.',
    symbol: 'cajado-e-runas',
    element: 'o círculo ritual sob a lua',
  },
  heroi: {
    id: 'heroi',
    name: 'O Herói',
    epithet: 'O Portador da Espada Justa',
    desire: 'Provar valor próprio através de ação corajosa e competente',
    fear: 'Fraqueza, vulnerabilidade, ser visto como covarde',
    shadow: 'Arrogância, necessidade compulsiva de conquista, negação da própria limitação',
    defenseMechanisms: 'Compensação, formação reativa contra a passividade, negação da vulnerabilidade',
    clinicalNote:
      'Corresponde à jornada de individuação clássica (Campbell/Jung) e à superação do complexo materno. Em excesso, indica defesa maníaca contra afetos depressivos e traços narcisistas de hipercompetência.',
    symbol: 'espada-erguida',
    element: 'o portal do dragão',
  },
  amante: {
    id: 'amante',
    name: 'O Amante',
    epithet: 'O Coração em Chamas',
    desire: 'Intimidade, êxtase relacional e experiência sensorial plena',
    fear: 'Estar só, não ser desejado ou amado, perder o objeto de amor',
    shadow: 'Fusão simbiótica; perda de fronteiras egoicas; ciúme destrutivo',
    defenseMechanisms: 'Idealização do objeto, negação da perda, fusão simbiótica',
    clinicalNote:
      'Relaciona-se à pulsão de Eros e à busca de fusão descrita na relação objetal. Em padrão rígido aproxima-se de dependência afetiva e de dificuldades de diferenciação self-objeto (Kernberg, Mahler).',
    symbol: 'coracao-e-rosa',
    element: 'o jardim ao entardecer',
  },
  bobo: {
    id: 'bobo',
    name: 'O Bobo da Corte',
    epithet: 'O Arauto da Verdade Disfarçada',
    desire: 'Viver o momento presente com alegria plena; romper convenções pela leveza',
    fear: 'Ser entediante, levar tudo (e a si mesmo) demais a sério',
    shadow: 'Evitação defensiva do afeto sério através do humor; fuga da profundidade emocional',
    defenseMechanisms: 'Humor como defesa, negação por deslocamento cômico, regressão lúdica',
    clinicalNote:
      'O humor aqui opera como mecanismo de defesa maduro (Vaillant), mas quando compulsivo pode mascarar afeto depressivo subjacente — padrão descrito como "riso defensivo" na clínica do caráter histriônico.',
    symbol: 'mascara-bufao',
    element: 'o salão do banquete',
  },
  criador: {
    id: 'criador',
    name: 'O Criador',
    epithet: 'O Forjador de Mundos',
    desire: 'Criar algo de valor duradouro; dar forma a uma visão',
    fear: 'Mediocridade; visão sem execução; a obra imperfeita',
    shadow: 'Perfeccionismo paralisante; narcisismo da obra em detrimento do vínculo',
    defenseMechanisms: 'Sublimação, perfeccionismo como defesa, isolamento produtivo',
    clinicalNote:
      'Expressão da sublimação freudiana clássica — transformação da pulsão em produção simbólica valorizada. Em excesso, aproxima-se de traços obsessivos e de perfeccionismo autopunitivo descritos na personalidade obsessivo-compulsiva.',
    symbol: 'martelo-e-bigorna',
    element: 'a forja incandescente',
  },
};

const ARCHETYPE_ORDER = [
  'inocente',
  'orfao',
  'guerreiro',
  'cuidador',
  'explorador',
  'sabio',
  'rebelde',
  'mago',
  'heroi',
  'amante',
  'bobo',
  'criador',
];
